def get_index(s, t):
    s_len = len(s)
    t_len = len(t)
    ans = list()

    for i in range(s_len-t_len):
        if s[i:i+t_len] == t:
            ans.append(i+1)
    return ans

if __name__ == "__main__":
    s = "TCATCGGTCGAGCATCGGTCACATCGGTCATCGGTCAATTCATCGGTCCCCATCGGTGCATCGGTAACATCGGTTCGACATCGGTGTCATCGGTGTATGTATCTCATCGGTCATCGGTAGGCATCGGTTTGGGCATCGGTACTACATCGGTCATCGGTAACCCATCGGTAATAGAATTTTCCATCGGTGTAGCACCATCGGTTCGGCATCGGTGACTCTCATCGGTGTTTCTGCATCGGTCATCGGTACCGCATCGGTCCGACACATCGGTTACATCGGTCATCGGTCCACATCGGTTTGACACCAATTTTCATCGGTGCATCGGTGTGGGAACATCGGTTTATTGCACATCGGTACATCGGTCATCGGTACATCGGTGCATCGGTCATCGGTCATCGGTCCCATCGGTCATCGGTCATCGGTACATCGGTGGATAGCCATCGGTTCACAACCGGATTCATCGGTTCCATCGGTCCCATCGGTAGGTCATCGGTACGGGTTCCATCGGTGGGTCATCGGTGTGCATCGGTCATCGGTTTTCACATCGGTCATCGGTACATCGGTCATCGGTCATCGGTCGAGCGTTGCCATCGGTCCAGTACTGCATCGGTCTCAAAAGCGATATGAAGCGCAGAACAACCCATCGGTCATCGGTAAATCATCGGTCCATCGGTGCATCGGTTCATCGGTTCATCGGTACATCGGTCATCGGTTCATCGGTCATCGGTCATCGGTACATCGGTGAGACATCGGTGTCATCGGTGTGGCATCGGTTGACATCGGTAGCATCGGTCATCGGTTATATCATCGGTAGTCAGTCAGGGATTGCCCATCGGTATCATCGGTCATCGGTAAGGTCACGCATCGGTCATCGGTAAGCATCGGTTTACATCGGTCGCATCGGTCAGCTTGTACACCAGTTCATCGGTTTTCATCGGTGATGAACATCGGTCATCGGT"
    t = "CATCGGTCA"

    print(get_index(s,t))
